package com.cicconesoftware.tripsentinel.entity;

import java.util.HashSet;
import java.util.Set;

import com.cicconesoftware.tripsentinel.entity.enums.CheckInMethodType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

// JPA entity for check-in methods supported by sessions
@Entity
@Table(name = "check_in_methods")
public class CheckInMethod {

    // Primary key for the CheckInMethod entity; auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Display name for the method, such as SMS or phone call
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, unique = true)
    private CheckInMethodType name;

    // Default constructor required by JPA
    public CheckInMethod() {}

    // Sessions that can use this check-in method

    @ManyToMany(mappedBy = "checkInMethods")
    private Set<CheckInSession> sessions = new HashSet<>();


    // Getters and setters for the fields

    public Long getId() {
        return id;
    }
    

    public CheckInMethodType getName() {
        return name;
    }

    public void setName(CheckInMethodType name) {
        this.name = name;
    }

    public Set<CheckInSession> getSessions() {
        return sessions;
    }

    public void setSessions(Set<CheckInSession> sessions) {
        this.sessions = sessions;
    }
    
}
