package com.cicconesoftware.tripsentinel.entity;

import java.time.LocalDateTime;

import com.cicconesoftware.tripsentinel.entity.enums.SessionEventType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

// JPA entity for events recorded during a check-in session
@Entity
@Table(name = "session_events") 
public class SessionEvent {

    // Primary key for the SessionEvent entity; auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Type of event captured in the session
    @Enumerated(EnumType.STRING)
    @Column(name = "event_type", nullable = false, length = 50)
    private SessionEventType eventType;

    // Optional event note or description
    @Column(name = "note", columnDefinition = "TEXT")
    private String note;

    // When the event was created
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    // Default constructor required by JPA
    public SessionEvent() {
    }

    // Link back to the owning check-in session
    @ManyToOne
    @JoinColumn(name = "session_id", nullable = false)
    private CheckInSession session;


    // Getters and Setters
    public Long getId() {
        return id;
    }

    public CheckInSession getSession() {
        return session;
    }

    public void setSession(CheckInSession session) {
        this.session = session;
    }

    public SessionEventType getEventType() {
        return eventType;
    }

    public void setEventType(SessionEventType eventType) {
        this.eventType = eventType;
    }
    
    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}
