package com.cicconesoftware.tripsentinel.entity;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import com.cicconesoftware.tripsentinel.entity.enums.UserStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

// JPA entity for the User table in the database
@Entity
@Table(name = "users")
public class User {
    
    // Primary key for the User entity; auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // User personal details stored in the users table
    @Column(name = "first_name", nullable = false, length = 100)
    private String firstName;

    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;   

    @Column(name = "phone_number", length = 50)
    private String phoneNumber;

    // Hashed password value used for authentication
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    // User status stored as string values from the UserStatus enum
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private UserStatus status;

    // Audit timestamps for when the user was created and last updated
    @Column(name  = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name  = "updated_at", nullable = false)
    private LocalDateTime updatedAt;


    // Default constructor required by JPA
    public User() {}


    // Relationships with other entities used to connect users to roles and sessions
    @ManyToMany
    @JoinTable(
        name = "user_roles",
        joinColumns = @JoinColumn(name = "user_id"),
        inverseJoinColumns = @JoinColumn(name = "role_id")
    )
    private Set<Role> roles = new HashSet<>();

    @OneToMany(mappedBy = "responder")
    private Set<ResponderAvailability> availabilitySlots = new HashSet<>();

    @OneToMany(mappedBy = "customer")
    private Set<CheckInSession> customerSessions = new HashSet<>();

    @OneToMany(mappedBy = "responder")
    private Set<CheckInSession> responderSessions = new HashSet<>();

    // Standard getters and setters for JPA property access


    public Long getId() {
        return id;
    }


    public String getFirstName() {
        return firstName;
    }


    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    public String getLastName() {
        return lastName;
    }


    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    public String getEmail() {
        return email;
    }


    public void setEmail(String email) {
        this.email = email;
    }


    public String getPhoneNumber() {
        return phoneNumber;
    }


    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


    public String getPasswordHash() {
        return passwordHash;
    }


    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }


    public UserStatus getStatus() {
        return status;
    }


    public void setStatus(UserStatus status) {
        this.status = status;
    }


    public LocalDateTime getCreatedAt() {
        return createdAt;
    }


    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }


    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }


    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    };

    public Set<Role> getRoles() {
    return roles;
}

public void setRoles(Set<Role> roles) {
    this.roles = roles;
}

public Set<ResponderAvailability> getAvailabilitySlots() {
    return availabilitySlots;
}

public void setAvailabilitySlots(Set<ResponderAvailability> availabilitySlots) {
    this.availabilitySlots = availabilitySlots;
}

public Set<CheckInSession> getCustomerSessions() {
    return customerSessions;
}

public void setCustomerSessions(Set<CheckInSession> customerSessions) {
    this.customerSessions = customerSessions;
}

public Set<CheckInSession> getResponderSessions() {
    return responderSessions;
}

public void setResponderSessions(Set<CheckInSession> responderSessions) {
    this.responderSessions = responderSessions;
}

   
    
}

